spring:
  # datasource
  datasource:
    url: jdbc:h2:mem:mailsender
    username: sa
    password:
  # h2
  h2:
    console:
      enabled: true
      path: /h2-console
  # jpa
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create-drop
  # flyway
  flyway:
    enabled: false
